### PR TITLE
fixed unmatched country names

### PR DESCRIPTION
**Pull request by brett-stephen**

### CODE REVIEW

**Comment by rahularoradfs** [comment]
Any programmatic checks to make sure that your list matches the WHO one, with none unmapped or missing either way?

**Comment by brett-stephen** [comment]
> 
> 
> Any programmatic checks to make sure that your list matches the WHO one, with none unmapped or missing either way?

I wrote a node js script to take the WHO csv and the GeoJson data and output errors in the matching process
 https://github.com/serotracker/shared_scripts/tree/main/CountryName_matching

Is this good enough in terms of doing it programmatically?

**Comment by rahularoradfs** [comment]
yep - good by me! let me know when you want a final review - once the PR is fully ready

**Comment by brett-stephen** [comment]
I've reviewed the names and tested against the incoming data, everything looks good.

**Review by ewanmay — APPROVED** [review]

**Pull request merged**
