### PR TITLE
Update en.json

### PR DESCRIPTION
**Pull request by floraguolr**
### Explore

- Check Desktop and on Mobile
- Summary Stats
- Map loads in ~8 seconds with loading spinner 
- Map has pins
- Country Modal - check all fields
- Pins modal (check each grade) - check all fields
- Filter info bubbles
- Select each filter and check options
- Execute a Filter for Risk of bias, Sex, and Date.
- Check the "Database up to date to:" date
- Check each footer item (Privacy policy etc.)

### Analyse
- Check tableau embed loads and is functional
- Check for double scrolling (the embed scrolls within the page) 

### Data
- Click each button
- Click a FAQ for functionality
- References table embed loads
    - Check that downloads are disabled.
- Data download link provides access to a downloadable CSV.
    - Download the CSV
- "terms of use" button

### Publications
- Cards all load with images
- Carousel is clickable
- Try 2 random items on the page for functional links

### About
- Page loads
- Scroll to bottom

### Check serotracker.com/broken
- 404 page loads and animation works

### Check serotracker.com/Canada 
- Check tableau embed loads and is functional
- Check for double scrolling (the embed scrolls within the page) 
- Check in French

### CODE REVIEW

**Comment by simonarocco** [comment]
Thanks @floraguolr. FYI next time just edit all the jsons for all 3 languages in 1 PR instead of separating by file. Also I think the French translation was fine as it was, it doesn't really make sense how it is now. Let's leave it as "Base de données à jour jusqu'à". Check with @grbdeveaux but should be fine

**Comment by grbdeveaux** [comment]
Yes the French phrasing is good. The most correct phrasing would be this:
"Base de données à jour jusqu'au"

"au" instead of "à"

**Comment by atatmaja** [comment]
Don't forget to update German (just use google translate for now). After that, it's good to merge!

**Review by atatmaja — APPROVED** [review]
LGTM

**Pull request merged**
